"""Finance implementation of Master's structural ``DayOpening`` boundary.

Master owns the calendar and transaction. Finance only knows how to determine whether the
required Finance state exists on an exact date and how to carry the exact preceding state
forward. The implementation deliberately does not import Master types.
"""

from __future__ import annotations

from datetime import date
from typing import Any

from psycopg import sql

from app.finance.db import FinanceDataNotReady, get_db_schema

__all__ = ["FinanceDayOpening"]

# ``DAY`` is already Finance's generic daily state vocabulary (as opposed to the seeded
# ``DAY0``/``DAY30`` snapshots and the approval-specific ``H1_COMMITMENT`` state).
DAY_OPEN_STATE_TYPE = "DAY"


class FinanceDayOpening:
    """Open an exact calendar-day Finance state using the caller's connection only."""

    def is_open(self, conn: Any, *, as_of: date) -> bool:
        """Return whether the active runtime axis has a state exactly on ``as_of``."""
        sim_run_id, financing_mode = self._runtime_axis(conn)
        schema = sql.Identifier(get_db_schema())
        query = self._exact_state_query(schema)
        with conn.cursor() as cursor:
            cursor.execute(
                query,
                {
                    "sim_run_id": sim_run_id,
                    "financing_mode": financing_mode,
                    "state_date": as_of,
                },
            )
            rows = cursor.fetchall()
        if len(rows) > 1:
            raise FinanceDataNotReady("finance_state_ambiguous")
        return bool(rows)

    def open_day(self, conn: Any, *, as_of: date, carry_from: date) -> None:
        """Carry the exact ``carry_from`` state to ``as_of`` idempotently.

        Every non-identity field is a carried Finance snapshot. This is the same established
        rule used by the approval transition's ``INSERT ... SELECT``. ``financial_limit_krw``
        is generated by PostgreSQL and is intentionally absent from the insert.
        """
        sim_run_id, financing_mode = self._runtime_axis(conn)
        if self._has_exact_state(
            conn,
            as_of=as_of,
            sim_run_id=sim_run_id,
            financing_mode=financing_mode,
        ):
            return
        if not self._has_exact_state(
            conn,
            as_of=carry_from,
            sim_run_id=sim_run_id,
            financing_mode=financing_mode,
        ):
            raise FinanceDataNotReady("historical_finance_position")

        schema = sql.Identifier(get_db_schema())
        with conn.cursor() as cursor:
            cursor.execute(
                self._carry_forward_query(schema),
                {
                    "finance_state_id": (f"FIN-DAY-{sim_run_id}-{financing_mode}-{as_of:%Y%m%d}"),
                    "sim_run_id": sim_run_id,
                    "financing_mode": financing_mode,
                    "as_of": as_of,
                    "carry_from": carry_from,
                    "state_type": DAY_OPEN_STATE_TYPE,
                    "note": f"하루 넘김이 {carry_from} 재무 상태에서 물려받아 세운 행",
                },
            )

    @staticmethod
    def _runtime_axis(conn: Any) -> tuple[str, str]:
        """Read the one active Finance axis without opening another connection."""
        schema = sql.Identifier(get_db_schema())
        query = sql.SQL(
            "SELECT DISTINCT sim_run_id, financing_mode FROM {}.v_current_finance_state"
        ).format(schema)
        with conn.cursor() as cursor:
            cursor.execute(query)
            rows = cursor.fetchall()
        if not rows:
            raise FinanceDataNotReady("historical_finance_position")
        if len(rows) != 1:
            raise FinanceDataNotReady("finance_runtime_axis_ambiguous")
        row = rows[0]
        if isinstance(row, dict):
            return str(row["sim_run_id"]), str(row["financing_mode"])
        return str(row[0]), str(row[1])

    @staticmethod
    def _has_exact_state(
        conn: Any,
        *,
        as_of: date,
        sim_run_id: str,
        financing_mode: str,
    ) -> bool:
        schema = sql.Identifier(get_db_schema())
        query = FinanceDayOpening._exact_state_query(schema)
        with conn.cursor() as cursor:
            cursor.execute(
                query,
                {
                    "sim_run_id": sim_run_id,
                    "financing_mode": financing_mode,
                    "state_date": as_of,
                },
            )
            rows = cursor.fetchall()
        if len(rows) > 1:
            raise FinanceDataNotReady("finance_state_ambiguous")
        return bool(rows)

    @staticmethod
    def _exact_state_query(schema: sql.Identifier) -> sql.Composed:
        return sql.SQL(
            """
            SELECT finance_state_id
            FROM {}.finance_states
            WHERE sim_run_id = %(sim_run_id)s
              AND financing_mode = %(financing_mode)s
              AND state_date = %(state_date)s
            LIMIT 2
            """
        ).format(schema)

    @staticmethod
    def _carry_forward_query(schema: sql.Identifier) -> sql.Composed:
        return sql.SQL(
            """
            INSERT INTO {schema}.finance_states (
                finance_state_id, sim_run_id, state_date, state_type, financing_mode,
                current_cash_krw, minimum_operating_cash_krw, committed_outflows_krw,
                unsettled_purchase_payables_krw, receivables_krw,
                inventory_book_value_krw, operational_inventory_value_krw,
                current_debt_krw, recommended_loan_amount_krw, note
            )
            SELECT
                %(finance_state_id)s, base.sim_run_id, %(as_of)s, %(state_type)s,
                base.financing_mode,
                base.current_cash_krw, base.minimum_operating_cash_krw,
                base.committed_outflows_krw, base.unsettled_purchase_payables_krw,
                base.receivables_krw, base.inventory_book_value_krw,
                base.operational_inventory_value_krw, base.current_debt_krw,
                base.recommended_loan_amount_krw, %(note)s
            FROM {schema}.finance_states base
            WHERE base.sim_run_id = %(sim_run_id)s
              AND base.financing_mode = %(financing_mode)s
              AND base.state_date = %(carry_from)s
            ON CONFLICT (finance_state_id) DO NOTHING
            """
        ).format(schema=schema)
